### ISSUE TITLE
Start adding doc strings.

### ISSUE THREAD

**Issue by kovitikus** [kovitikus/hecate#16]
Update all current code to have documentation strings for every method and function. Explain yourself!

**Comment by kovitikus** [comment]
You don't need an issue open for this. You already know that you should have documentation strings. If you are too stupid or lazy to add them, no amount of open issues will change your behavior.

**Comment by The-Archemist** [comment]
> You don't need an issue open for this. You already know that you should have documentation strings. If you are too stupid or lazy to add them then no amount of open issues will change your behavior.

Inspiring.
